name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!
      - run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Create styled proverbs
        uses: alexrogalskiy/github-action-proverbs@master
        with:
          language: 'thai'
          pattern: 'wiggle'
          name: 'proverb'
          path: 'images'
      # - uses: actions/hello-world-docker-action@v2 
      #   with: 
      #     who-to-greet: 'YNS!!!'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # - run: npm ci
      # - run: npm run sample
      # - run: cat README.md
      # - run: git log

  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is the second job in this workflow.

